name: bicikelj_parser
description: A application to query bicycle data from Biciklej.si
version: 1.0.0

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  dio: ^4.0.6
  sqflite_common_ffi: ^2.1.1+1
  path: ^1.8.2
  logger: ^1.1.0
  args: ^2.3.1
  latlong2: ^0.8.1
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
